{"uuid": "3c855152-f4b9-4e63-8791-b1cfe8f2687e", "children": ["0f7fe047-b35c-4a69-9fe4-5effe9604317"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT\n  (Session info: chrome=134.0.6998.89)\nStacktrace:\n\tGetHandleVerifier [0x00007FF70CBDFE45+26629]\n\t(No symbol) [0x00007FF70CB46010]\n\t(No symbol) [0x00007FF70C9D931A]\n\t(No symbol) [0x00007FF70C9D5D10]\n\t(No symbol) [0x00007FF70C9C68C9]\n\t(No symbol) [0x00007FF70C9C8638]\n\t(No symbol) [0x00007FF70C9C6BD6]\n\t(No symbol) [0x00007FF70C9C6656]\n\t(No symbol) [0x00007FF70C9C631A]\n\t(No symbol) [0x00007FF70C9C3E9F]\n\t(No symbol) [0x00007FF70C9C478C]\n\t(No symbol) [0x00007FF70C9DD16A]\n\t(No symbol) [0x00007FF70CA8102E]\n\t(No symbol) [0x00007FF70CA57AAA]\n\t(No symbol) [0x00007FF70CA80169]\n\t(No symbol) [0x00007FF70CA57883]\n\t(No symbol) [0x00007FF70CA20550]\n\t(No symbol) [0x00007FF70CA21803]\n\tGetHandleVerifier [0x00007FF70CF372BD+3529853]\n\tGetHandleVerifier [0x00007FF70CF4DA22+3621858]\n\tGetHandleVerifier [0x00007FF70CF424D3+3575443]\n\tGetHandleVerifier [0x00007FF70CCAB77A+860474]\n\t(No symbol) [0x00007FF70CB5088F]\n\t(No symbol) [0x00007FF70CB4CBC4]\n\t(No symbol) [0x00007FF70CB4CD66]\n\t(No symbol) [0x00007FF70CB3C2C9]\n\tBaseThreadInitThunk [0x00007FFE70BA7614+20]\n\tRtlUserThreadStart [0x00007FFE70CE26A1+33]\n\n", "trace": "  File \"C:\\Users\\KIIT\\PycharmProjects\\pythonProject6\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\KIIT\\PycharmProjects\\pythonProject6\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\KIIT\\PycharmProjects\\pythonProject6\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KIIT\\PycharmProjects\\pythonProject6\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KIIT\\PycharmProjects\\pythonProject6\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\KIIT\\PycharmProjects\\pythonProject6\\Test_Package\\conftest.py\", line 32, in setup\n    driver.get(loginpage_url)\n  File \"C:\\Users\\KIIT\\PycharmProjects\\pythonProject6\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\KIIT\\PycharmProjects\\pythonProject6\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\KIIT\\PycharmProjects\\pythonProject6\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742372564683, "stop": 1742372608276}], "start": 1742372564683, "stop": 1742372608444}